# Generated by Django 5.2.8 on 2025-11-23 08:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('N', 'North'), ('S', 'South'), ('E', 'East'), ('W', 'West'), ('NE', 'North-East'), ('NW', 'North-West'), ('SE', 'South-East'), ('SW', 'South-West')], help_text='Direction to travel', max_length=2)),
                ('distance', models.IntegerField(help_text='Distance in nautical miles (must be greater than zero)', validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField(help_text='Description of this instruction')),
                ('risk_level', models.IntegerField(help_text='Risk level (0-100) for the seas after this turn', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('previous_instruction', models.ForeignKey(blank=True, help_text='Link to the previous instruction in the route', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_instructions', to='compass.instruction')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
